spring.config.import=optional:file:./.env.properties
spring.application.name=Micro-Learning API

spring.datasource.url=jdbc:h2:mem:micro;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true
spring.h2.console.path=/h2
